---
host: gitlab
become: true
gather_facts: false
task:
  - name: Create a new ext4 primary partition
    community.general.parted:
      device: /dev/sdb
      number: 1
      state: present
      fs_type: ext4

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /mnt/data
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Mount volume sdb1 to data folder
    ansible.posix.mount:
      path: /mnt/data
      src: /dev/sdb1
      fstype: ext4
      state: present