[localhost]
localhost

[proxmox]
10.20.15.6 hostname=dell-node1
10.20.15.7 hostname=dell-node2
10.20.15.15 hostname=pve-node1
10.20.15.16 hostname=hp-node3
10.20.15.17 hostname=hp-node4
10.20.15.18 hostname=hp-node5
10.20.15.19 hostname=hp-node6

[proxmox:vars]
ansible_user=root
ansible_ssh_pass=5ruXurur!