---
- name: Install zabbix
  hosts: zabbix
  tasks:
  - name: Set credentials to access Zabbix Server API
    ansible.builtin.set_fact:
      ansible_user: Admin
      ansible_httpapi_pass: zabbix
  - name: Create a new host or rewrite an existing host's info (Zabbix <= 7.0)
# Set task level following variables for Zabbix Server host in task
    vars:
      ansible_network_os: community.zabbix.zabbix
      ansible_connection: httpapi
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: true
      ansible_httpapi_validate_certs: false
#      ansible_zabbix_url_path: "zabbixeu"  # If Zabbix WebUI runs on non-default (zabbix) path ,e.g. http://<FQDN>/zabbixeu
    become: false
    delegate_to: zabbix-example-fqdn.org# you can use delegate_to or task level ansible_host like next example
    community.zabbix.zabbix_host:
      host_name: log-server
      visible_name: log-server
      description: Test host from zabbix api
      host_groups: 
        - Linux servers
      link_templates:
        - Linux by Zabbix agent
      status: enabled
      state: present
      interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: 10.20.15.43
        dns: ""
        port: "10050"
      tags:
      - tag: Test