---
# tasks file for proxy
- name: Install common utils
  apt:
    name: software-properties-common
    install_recommends: no

- name: Add Haproxy stable repository from PPA and install its signing key on Debian target
  ansible.builtin.apt_repository:
    repo: 'ppa:vbernat/haproxy-3.0'

- name: Install 
  apt:
    name: haproxy
    update_cache: yes

- name: Copy haproxy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0600'
  register: haproxy_conf
  notify: Restart haproxy

