---
# tasks file for proxy
- name: Install common utils
  apt:
    name: software-properties-common
    install_recommends: no

- name: Add Haproxy stable repository from PPA and install its signing key on Debian target
  ansible.builtin.apt_repository:
    repo: 'ppa:vbernat/haproxy-3.0'

- name: Install packages Haproxy and Keepalived
  apt:
    name: 
      - haproxy
      - keepalived
    update_cache: yes

- name: Copy haproxy haproxy.cfg to master
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0600'
  register: haproxy_conf
  notify: Restart haproxy

- name: Copy keepalived.conf to master
  ansible.builtin.template:
    src: keepalived.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0600'
  notify: Restart keepalived